build:
    dependencies:
        before:
            - sudo apt-get install -y software-properties-common
            - sudo add-apt-repository ppa:pinepain/libv8-6.3
            - sudo apt-get update
            - sudo apt-get install -y libv8-6.3 libv8-6.3-dev libv8-6.3-dbg
            - pecl install v8
            - pecl install ref

checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
      - "vendor/"
      - "tests/"
tools:
  external_code_coverage: true
